# Models: Parametric vs DML

In [1]:
import pandas as pd
import numpy as np
import plotly.express as px
from sklearn.linear_model import ElasticNetCV
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
import sys
from pathlib import Path
import statsmodels.api as sm
from econml.dml import LinearDML, CausalForestDML
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import KFold


PROJECT_ROOT = Path.cwd().parent  # assumes notebooks/ is one level below root
sys.path.append(str(PROJECT_ROOT))

from src.load_data import load_feature
from src.results import sm_extract, econml_ate_row

c:\Users\danil\anaconda3\envs\vair312\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
df = load_feature()
df.head()

,host_response_rate,host_acceptance_rate,host_is_superhost,host_listings_count,host_total_listings_count,host_verifications,host_has_profile_pic,host_identity_verified,accommodates,bathrooms,...,amenity_Dedicated workspace,amenity_Toaster,amenity_Freezer,amenity_Shower gel,amenity_First aid kit,amenity_Dining table,amenity_Cleaning products,amenity_Self check-in,amenity_Fire extinguisher,amenity_Long term stays allowed
0,1.00,0.96,1,1.098612,1.791759,2,1,1,1,1.0,...,1,1,1,1,1,1,0,1,1,1
1,0.88,0.88,1,1.386294,2.833213,3,1,1,6,2.0,...,1,1,1,0,0,1,1,0,0,1
2,1.00,0.98,0,1.386294,4.691348,2,1,1,4,1.0,...,0,0,0,0,0,0,0,0,0,0
3,1.00,0.91,0,0.693147,0.693147,3,1,1,5,1.5,...,1,0,0,0,0,0,0,1,1,0
4,1.00,1.00,1,1.098612,1.609438,2,1,1,2,0.0,...,1,0,0,0,1,0,0,1,1,0

In [3]:
df.dtypes.value_counts()

bool       131
int64       46
float64     20
Name: count, dtype: int64

In [4]:
df.select_dtypes(include="object").columns.tolist()

[]

## Parametric model

In [5]:
#first spec without borough
borough_columns = [i for i in df.columns if "borough" in i ]

In [6]:
#outcome and treatment variable
y = df["log_price"]
d =df["log_rivals_500m"]

#exclude and controls
exclude = {"log_price", "log_rivals_500m", "loc_fe", "log_rivals_c_sq", "log_rivals_c"}
X = df[[c for c in df.columns if (c not in exclude)]]


#controls and treatment
Z = pd.concat([d,X], axis=1)

#adding constant
Z = sm.add_constant(Z, has_constant="add")

#changing data types
y = y.astype(float)
Z = Z.astype(float)

Z.shape

(42898, 194)

In [7]:
#running model
ols2 = sm.OLS(y, Z).fit(
    cov_type="cluster",
    cov_kwds={"groups": df["loc_fe"]}
)

print(ols2.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:              log_price   R-squared:                       0.727
Model:                            OLS   Adj. R-squared:                  0.725
Method:                 Least Squares   F-statistic:                 3.547e+04
Date:                Thu, 26 Feb 2026   Prob (F-statistic):          3.35e-197
Time:                        16:55:20   Log-Likelihood:                -20674.
No. Observations:               42898   AIC:                         4.174e+04
Df Residuals:                   42704   BIC:                         4.342e+04
Df Model:                         193
Covariance Type:              cluster
===================================================================================================
                                      coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------------------------
const                               4.3425      0.110     39.468      0.000       4.127       4.558
log_rivals_500m                     0.0187      0.012      1.536      0.125      -0.005       0.042
host_response_rate                 -0.0060      0.021     -0.290      0.772      -0.046       0.034
host_acceptance_rate               -0.0497      0.013     -3.876      0.000      -0.075      -0.025
host_is_superhost                   0.1013      0.012      8.618      0.000       0.078       0.124
host_listings_count                 0.0044      0.012      0.369      0.712      -0.019       0.028
host_total_listings_count          -0.0258      0.010     -2.635      0.008      -0.045      -0.007
host_verifications                  0.0221      0.010      2.308      0.021       0.003       0.041
host_has_profile_pic                0.0271      0.019      1.409      0.159      -0.011       0.065
host_identity_verified             -0.0239      0.012     -1.958      0.050      -0.048       2e-05
accommodates                        0.0827      0.004     18.645      0.000       0.074       0.091
bathrooms                           0.0954      0.012      7.655      0.000       0.071       0.120
bedrooms                            0.1533      0.010     15.333      0.000       0.134       0.173
beds                               -0.0252      0.005     -5.298      0.000      -0.035      -0.016
minimum_nights                     -0.0005      0.000     -2.700      0.007      -0.001      -0.000
maximum_nights                      0.0117      0.003      4.219      0.000       0.006       0.017
number_of_reviews                  -0.0007   5.17e-05    -12.886      0.000      -0.001      -0.001
review_scores_rating                0.1312      0.015      8.487      0.000       0.101       0.162
review_scores_accuracy             -0.0362      0.012     -3.142      0.002      -0.059      -0.014
review_scores_cleanliness           0.1306      0.011     11.427      0.000       0.108       0.153
review_scores_checkin              -0.0615      0.008     -7.324      0.000      -0.078      -0.045
review_scores_communication        -0.0643      0.012     -5.511      0.000      -0.087      -0.041
review_scores_location              0.0743      0.015      4.835      0.000       0.044       0.104
review_scores_value                -0.1037      0.011     -9.100      0.000      -0.126      -0.081
instant_bookable                    0.0139      0.008      1.776      0.076      -0.001       0.029
calculated_host_listings_count      0.0015      0.000     10.202      0.000       0.001       0.002
experience                          0.0035      0.001      3.601      0.000       0.002       0.005
desc_dummy                         -0.1459      0.024     -5.962      0.000      -0.194      -0.098
about_dummy                         0.0071      0.008      0.835      0.404      -0.010       0.024
overveiw_dummy                      0.0241      0.008      2.965      0.003       0.008       0.040
shared                             -1.2430      0.102    -12.132      0.000      -1.444      -1.042
entire                              0.0058      0.032      0.182      0.855      -0.057       0.068
private                            -0.5997      0.037    -16.042      0.000      -0.673      -0.526
borough_Barnet                      0.0543      0.087      0.623      0.533      -0.117       0.225
borough_Bexley                     -0.0734      0.064     -1.148      0.251      -0.199       0.052
borough_Brent                       0.1954      0.085      2.304      0.021       0.029       0.362
borough_Bromley                     0.0789      0.096      0.821      0.412      -0.109       0.267
borough_Camden                      0.1260      0.074      1.694      0.090      -0.020       0.272
borough_City of London              0.3193      0.068      4.671      0.000       0.185       0.453
borough_Croydon                     0.1352      0.099      1.361      0.174      -0.060       0.330
borough_Ealing                      0.1997      0.090      2.229      0.026       0.024       0.375
borough_Enfield                     0.1248      0.075      1.669      0.095      -0.022       0.271
borough_Greenwich                  -0.0131      0.079     -0.166      0.868      -0.167       0.141
borough_Hackney                    -0.0213      0.063     -0.340      0.734      -0.144       0.101
borough_Hammersmith and Fulham      0.2409      0.096      2.506      0.012       0.052       0.429
borough_Haringey                    0.0893      0.079      1.130      0.258      -0.066       0.244
borough_Harrow                      0.1554      0.099      1.569      0.117      -0.039       0.349
borough_Havering                    0.0657      0.051      1.284      0.199      -0.035       0.166
borough_Hillingdon                  0.1505      0.095      1.579      0.114      -0.036       0.337
borough_Hounslow                    0.3168      0.095      3.326      0.001       0.130       0.503
borough_Islington                   0.0713      0.066      1.078      0.281      -0.058       0.201
borough_Kensington and Chelsea      0.2931      0.092      3.174      0.002       0.112       0.474
borough_Kingston upon Thames        0.2436      0.100      2.437      0.015       0.048       0.439
borough_Lambeth                     0.1161      0.082      1.422      0.155      -0.044       0.276
borough_Lewisham                   -0.0869      0.077     -1.129      0.259      -0.238       0.064
borough_Merton                      0.2191      0.112      1.961      0.050     6.8e-05       0.438
borough_Newham                     -0.0345      0.067     -0.516      0.606      -0.166       0.097
borough_Redbridge                  -0.0320      0.060     -0.532      0.595      -0.150       0.086
borough_Richmond upon Thames        0.4345      0.097      4.490      0.000       0.245       0.624
borough_Southwark                  -0.0434      0.087     -0.498      0.618      -0.214       0.127
borough_Sutton                      0.2760      0.186      1.487      0.137      -0.088       0.640
borough_Tower Hamlets              -0.0330      0.063     -0.525      0.599      -0.156       0.090
borough_Waltham Forest             -0.1011      0.057     -1.760      0.078      -0.214       0.011
borough_Wandsworth                  0.2111      0.110      1.919      0.055      -0.005       0.427
borough_Westminster                 0.2746      0.083      3.312      0.001       0.112       0.437
fe_1                               -0.4731      0.071     -6.685      0.000      -0.612      -0.334
fe_2                               -0.5494      0.074     -7.431      0.000      -0.694      -0.405
fe_3                               -0.4523      0.069     -6.581      0.000      -0.587      -0.318
fe_4                               -0.4719      0.059     -8.021      0.000      -0.587      -0.357
fe_5                               -0.6074      0.063     -9.675      0.000      -0.730      -0.484
fe_6                               -0.2176      0.066     -3.315      0.001      -0.346      -0.089
fe_7                               -0.6591      0.079     -8.313      0.000      -0.815      -0.504
fe_8                               -0.5131      0.063     -8.113      0.000      -0.637      -0.389
fe_9                               -0.4878      0.061     -8.003      0.000      -0.607      -0.368
fe_10                              -0.6026      0.072     -8.319      0.000      -0.745      -0.461
fe_11                              -0.3350      0.020    -16.532      0.000      -0.375      -0.295
fe_12                              -0.4578      0.045    -10.201      0.000      -0.546      -0.370
fe_13                              -0.5453      0.065     -8.350      0.000      -0.673      -0.417
fe_14                              -0.7574      0.073    -10.399      0.000      -0.900      -0.615
fe_15                              -0.6047      0.080     -7.589      0.000      -0.761      -0.449
fe_16                              -0.3288      0.058     -5.705      0.000      -0.442      -0.216
fe_17                              -0.1417      0.064     -2.206      0.027      -0.268      -0.016
fe_18                              -0.9918      0.176     -5.638      0.000      -1.337      -0.647
fe_19                              -0.3092      0.057     -5.436      0.000      -0.421      -0.198
fe_20                              -0.4856      0.070     -6.897      0.000      -0.624      -0.348
fe_21                              -0.5659      0.065     -8.725      0.000      -0.693      -0.439
fe_22                              -0.7136      0.055    -12.982      0.000      -0.821      -0.606
fe_23                              -0.3004      0.077     -3.909      0.000      -0.451      -0.150
fe_24                              -0.8451      0.066    -12.737      0.000      -0.975      -0.715
fe_25                              -0.6742      0.063    -10.764      0.000      -0.797      -0.551
fe_26                              -0.6442      0.056    -11.412      0.000      -0.755      -0.534
fe_27                              -0.7657      0.091     -8.424      0.000      -0.944      -0.588
fe_28                              -0.0359      0.040     -0.905      0.366      -0.114       0.042
fe_29                              -0.5612      0.083     -6.795      0.000      -0.723      -0.399
fe_30                              -0.8664      0.068    -12.798      0.000      -0.999      -0.734
fe_31                              -0.2996      0.060     -4.973      0.000      -0.418      -0.182
fe_32                              -0.6142      0.072     -8.579      0.000      -0.754      -0.474
fe_33                              -0.6088      0.076     -7.960      0.000      -0.759      -0.459
fe_34                              -0.5248      0.017    -30.586      0.000      -0.558      -0.491
fe_35                              -0.6005      0.058    -10.320      0.000      -0.715      -0.486
fe_36                              -0.4375      0.072     -6.107      0.000      -0.578      -0.297
fe_37                              -0.5795      0.070     -8.239      0.000      -0.717      -0.442
fe_38                              -0.7128      0.077     -9.279      0.000      -0.863      -0.562
fe_39                              -0.5888      0.066     -8.916      0.000      -0.718      -0.459
fe_40                              -0.0369      0.046     -0.805      0.421      -0.127       0.053
fe_41                              -0.5843      0.070     -8.363      0.000      -0.721      -0.447
fe_42                              -0.6976      0.080     -8.706      0.000      -0.855      -0.541
fe_43                              -0.3311      0.063     -5.294      0.000      -0.454      -0.208
fe_44                              -0.4910      0.056     -8.755      0.000      -0.601      -0.381
fe_45                              -0.7424      0.048    -15.315      0.000      -0.837      -0.647
fe_46                              -0.5042      0.030    -17.028      0.000      -0.562      -0.446
fe_47                              -0.3947      0.052     -7.607      0.000      -0.496      -0.293
fe_48                              -0.3314      0.053     -6.205      0.000      -0.436      -0.227
fe_49                              -0.5798      0.080     -7.208      0.000      -0.737      -0.422
fe_50                              -0.3588      0.083     -4.343      0.000      -0.521      -0.197
fe_51                              -0.4274      0.071     -5.982      0.000      -0.567      -0.287
fe_52                              -0.2444      0.023    -10.416      0.000      -0.290      -0.198
fe_53                              -0.6154      0.076     -8.062      0.000      -0.765      -0.466
fe_54                              -0.6355      0.034    -18.768      0.000      -0.702      -0.569
fe_55                              -0.7322      0.079     -9.257      0.000      -0.887      -0.577
fe_56                              -0.6028      0.068     -8.832      0.000      -0.737      -0.469
fe_57                              -0.5493      0.081     -6.764      0.000      -0.708      -0.390
fe_58                              -0.3703      0.068     -5.414      0.000      -0.504      -0.236
fe_59                              -0.3469      0.065     -5.345      0.000      -0.474      -0.220
fe_60                              -0.2358      0.057     -4.125      0.000      -0.348      -0.124
fe_61                              -0.5288      0.082     -6.477      0.000      -0.689      -0.369
fe_62                              -0.4474      0.046     -9.790      0.000      -0.537      -0.358
fe_63                              -0.6643      0.066    -10.053      0.000      -0.794      -0.535
fe_64                              -0.5091      0.066     -7.726      0.000      -0.638      -0.380
fe_65                              -0.7547      0.096     -7.899      0.000      -0.942      -0.567
fe_66                              -0.1635      0.060     -2.710      0.007      -0.282      -0.045
fe_67                              -0.9074      0.159     -5.715      0.000      -1.219      -0.596
fe_68                              -0.5775      0.077     -7.467      0.000      -0.729      -0.426
fe_69                              -0.5334      0.079     -6.763      0.000      -0.688      -0.379
fe_70                              -0.5267      0.086     -6.096      0.000      -0.696      -0.357
fe_71                              -0.6060      0.082     -7.421      0.000      -0.766      -0.446
fe_72                              -0.5756      0.053    -10.817      0.000      -0.680      -0.471
fe_73                              -0.3852      0.055     -7.024      0.000      -0.493      -0.278
fe_74                              -0.3506      0.078     -4.469      0.000      -0.504      -0.197
fe_75                              -0.2290      0.079     -2.902      0.004      -0.384      -0.074
fe_76                              -0.5964      0.068     -8.813      0.000      -0.729      -0.464
fe_77                              -0.3528      0.079     -4.445      0.000      -0.508      -0.197
fe_78                              -0.2651      0.046     -5.741      0.000      -0.356      -0.175
fe_79                              -0.4714      0.074     -6.381      0.000      -0.616      -0.327
fe_80                              -0.3234      0.019    -17.210      0.000      -0.360      -0.287
fe_81                              -0.3991      0.057     -6.944      0.000      -0.512      -0.286
fe_82                              -0.5698      0.065     -8.790      0.000      -0.697      -0.443
fe_83                              -0.8747      0.073    -11.914      0.000      -1.019      -0.731
fe_84                              -0.3965      0.078     -5.073      0.000      -0.550      -0.243
fe_85                              -0.3514      0.046     -7.612      0.000      -0.442      -0.261
fe_86                              -0.1399      0.055     -2.566      0.010      -0.247      -0.033
fe_87                              -0.7085      0.084     -8.417      0.000      -0.873      -0.544
fe_88                              -0.7053      0.077     -9.158      0.000      -0.856      -0.554
fe_89                              -0.6385      0.062    -10.336      0.000      -0.760      -0.517
fe_90                              -0.5697      0.069     -8.203      0.000      -0.706      -0.434
fe_91                              -0.6595      0.061    -10.748      0.000      -0.780      -0.539
fe_92                              -0.1825      0.078     -2.345      0.019      -0.335      -0.030
fe_93                              -0.0418      0.008     -5.458      0.000      -0.057      -0.027
fe_94                              -0.6746      0.072     -9.358      0.000      -0.816      -0.533
fe_95                              -0.6663      0.076     -8.810      0.000      -0.814      -0.518
fe_96                              -0.2728      0.051     -5.392      0.000      -0.372      -0.174
fe_97                              -0.8771      0.080    -11.001      0.000      -1.033      -0.721
fe_98                              -0.6281      0.051    -12.325      0.000      -0.728      -0.528
fe_99                              -0.7043      0.070    -10.068      0.000      -0.841      -0.567
amenity_Wifi                       -0.0178      0.009     -2.050      0.040      -0.035      -0.001
amenity_Smoke alarm                -0.0156      0.016     -0.975      0.330      -0.047       0.016
amenity_Kitchen                     0.0120      0.017      0.715      0.474      -0.021       0.045
amenity_Washer                     -0.0198      0.011     -1.761      0.078      -0.042       0.002
amenity_Essentials                  0.0519      0.007      7.619      0.000       0.039       0.065
amenity_Iron                        0.0264      0.018      1.489      0.136      -0.008       0.061
amenity_Hot water                  -0.0938      0.012     -7.582      0.000      -0.118      -0.070
amenity_Hangers                    -0.0047      0.009     -0.523      0.601      -0.022       0.013
amenity_Carbon monoxide alarm      -0.0050      0.008     -0.594      0.552      -0.022       0.012
amenity_Hair dryer                  0.0309      0.010      3.056      0.002       0.011       0.051
amenity_Heating                    -0.0065      0.006     -1.142      0.253      -0.018       0.005
amenity_Bed linens                 -0.0102      0.008     -1.333      0.182      -0.025       0.005
amenity_TV                          0.0463      0.009      5.394      0.000       0.029       0.063
amenity_Dishes and silverware      -0.0415      0.010     -4.014      0.000      -0.062      -0.021
amenity_Refrigerator                0.0216      0.007      3.191      0.001       0.008       0.035
amenity_Cooking basics              0.0140      0.009      1.514      0.130      -0.004       0.032
amenity_Shampoo                     0.0033      0.010      0.323      0.746      -0.017       0.023
amenity_Microwave                  -0.0265      0.009     -2.856      0.004      -0.045      -0.008
amenity_Hot water kettle           -0.0150      0.013     -1.184      0.236      -0.040       0.010
amenity_Oven                        0.0068      0.009      0.775      0.438      -0.010       0.024
amenity_Dedicated workspace         0.0271      0.007      3.880      0.000       0.013       0.041
amenity_Toaster                     0.0205      0.009      2.319      0.020       0.003       0.038
amenity_Freezer                     0.0259      0.008      3.125      0.002       0.010       0.042
amenity_Shower gel                  0.0069      0.008      0.878      0.380      -0.009       0.022
amenity_First aid kit              -0.0030      0.007     -0.432      0.666      -0.017       0.011

c:\Users\danil\anaconda3\envs\vair312\Lib\site-packages\statsmodels\base\model.py:1894: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 193, but rank is 94
  warnings.warn('covariance of constraints does not have full '

In [8]:
beta = ols2.params["log_rivals_500m"]
se   = ols2.bse["log_rivals_500m"]
ci_l, ci_u = ols2.conf_int().loc["log_rivals_500m"].tolist()

print(beta, se, ci_l, ci_u)

0.018666948934831038 0.0121524492257893 -0.005151413871667652 0.04248531174132973

### Naive OLS, No FE

In [9]:
fe = [c for c in df.columns if c.startswith("fe_")]

In [10]:
#outcome and treatment variable
y_nl = df["log_price"]
d_nl =df["log_rivals_500m"]

#exclude and controls
exclude_nl = {"log_price", "log_rivals_500m", "loc_fe", "log_rivals_c", "log_rivals_c_sq"}
X_nl = df[[c for c in df.columns if (c not in exclude_nl) & (c not in fe) ]]


#controls and treatment
Z_nl = pd.concat([d_nl,X_nl], axis=1)

#adding constant
Z_nl = sm.add_constant(Z_nl, has_constant="add")

#changing data types
y_nl = y_nl.astype(float)
Z_nl = Z_nl.astype(float)

Z_nl.shape

(42898, 95)

In [11]:
print(f"{"log_rivals_c_sq" in Z_nl}")

False

In [12]:
#running model
ols1 = sm.OLS(y_nl, Z_nl).fit(
    cov_type="cluster",
    cov_kwds={"groups": df["loc_fe"]}
)

print(ols1.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:              log_price   R-squared:                       0.706
Model:                            OLS   Adj. R-squared:                  0.705
Method:                 Least Squares   F-statistic:                 1.083e+04
Date:                Thu, 26 Feb 2026   Prob (F-statistic):          1.07e-171
Time:                        16:55:20   Log-Likelihood:                -22265.
No. Observations:               42898   AIC:                         4.472e+04
Df Residuals:                   42803   BIC:                         4.554e+04
Df Model:                          94
Covariance Type:              cluster
===================================================================================================
                                      coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------------------------
const                               3.4444      0.091     37.902      0.000       3.266       3.623
log_rivals_500m                     0.0722      0.012      5.871      0.000       0.048       0.096
host_response_rate                 -0.0124      0.022     -0.559      0.576      -0.056       0.031
host_acceptance_rate               -0.0317      0.014     -2.317      0.020      -0.059      -0.005
host_is_superhost                   0.1136      0.013      8.931      0.000       0.089       0.138
host_listings_count                 0.0080      0.013      0.626      0.531      -0.017       0.033
host_total_listings_count          -0.0244      0.011     -2.244      0.025      -0.046      -0.003
host_verifications                  0.0143      0.010      1.415      0.157      -0.006       0.034
host_has_profile_pic                0.0265      0.019      1.421      0.155      -0.010       0.063
host_identity_verified             -0.0265      0.013     -1.986      0.047      -0.053      -0.000
accommodates                        0.0868      0.005     18.270      0.000       0.077       0.096
bathrooms                           0.1026      0.014      7.386      0.000       0.075       0.130
bedrooms                            0.1487      0.011     13.875      0.000       0.128       0.170
beds                               -0.0288      0.005     -5.856      0.000      -0.038      -0.019
minimum_nights                     -0.0006      0.000     -2.313      0.021      -0.001   -8.47e-05
maximum_nights                      0.0127      0.003      4.313      0.000       0.007       0.018
number_of_reviews                  -0.0006   5.58e-05    -11.506      0.000      -0.001      -0.001
review_scores_rating                0.1277      0.016      7.991      0.000       0.096       0.159
review_scores_accuracy             -0.0416      0.012     -3.471      0.001      -0.065      -0.018
review_scores_cleanliness           0.1379      0.012     11.439      0.000       0.114       0.161
review_scores_checkin              -0.0721      0.008     -8.597      0.000      -0.089      -0.056
review_scores_communication        -0.0742      0.013     -5.876      0.000      -0.099      -0.049
review_scores_location              0.1283      0.019      6.900      0.000       0.092       0.165
review_scores_value                -0.1141      0.011    -10.002      0.000      -0.137      -0.092
instant_bookable                    0.0170      0.009      1.964      0.050    3.39e-05       0.034
calculated_host_listings_count      0.0015      0.000      9.432      0.000       0.001       0.002
experience                          0.0031      0.001      3.218      0.001       0.001       0.005
desc_dummy                         -0.1220      0.025     -4.792      0.000      -0.172      -0.072
about_dummy                         0.0108      0.010      1.130      0.258      -0.008       0.030
overveiw_dummy                      0.0212      0.009      2.381      0.017       0.004       0.039
shared                             -1.2276      0.100    -12.333      0.000      -1.423      -1.033
entire                              0.0148      0.033      0.450      0.653      -0.050       0.079
private                            -0.6006      0.038    -15.954      0.000      -0.674      -0.527
borough_Barnet                      0.0375      0.026      1.459      0.145      -0.013       0.088
borough_Bexley                     -0.0215      0.037     -0.577      0.564      -0.095       0.052
borough_Brent                       0.1429      0.052      2.739      0.006       0.041       0.245
borough_Bromley                     0.0379      0.030      1.267      0.205      -0.021       0.097
borough_Camden                      0.3076      0.048      6.367      0.000       0.213       0.402
borough_City of London              0.5938      0.038     15.701      0.000       0.520       0.668
borough_Croydon                    -0.0426      0.057     -0.752      0.452      -0.154       0.068
borough_Ealing                      0.0625      0.031      2.003      0.045       0.001       0.124
borough_Enfield                     0.0757      0.022      3.517      0.000       0.034       0.118
borough_Greenwich                   0.0850      0.042      2.023      0.043       0.003       0.167
borough_Hackney                     0.1170      0.045      2.579      0.010       0.028       0.206
borough_Hammersmith and Fulham      0.1995      0.037      5.321      0.000       0.126       0.273
borough_Haringey                    0.0618      0.032      1.952      0.051      -0.000       0.124
borough_Harrow                      0.0758      0.034      2.239      0.025       0.009       0.142
borough_Havering                   -0.0283      0.054     -0.529      0.597      -0.133       0.077
borough_Hillingdon                  0.1389      0.028      4.914      0.000       0.083       0.194
borough_Hounslow                    0.1586      0.050      3.161      0.002       0.060       0.257
borough_Islington                   0.2354      0.051      4.645      0.000       0.136       0.335
borough_Kensington and Chelsea      0.4359      0.067      6.487      0.000       0.304       0.568
borough_Kingston upon Thames        0.1415      0.021      6.745      0.000       0.100       0.183
borough_Lambeth                     0.1757      0.092      1.917      0.055      -0.004       0.355
borough_Lewisham                   -0.0161      0.036     -0.448      0.654      -0.087       0.054
borough_Merton                      0.1309      0.051      2.589      0.010       0.032       0.230
borough_Newham                      0.1441      0.042      3.399      0.001       0.061       0.227
borough_Redbridge                   0.0029      0.037      0.080      0.936      -0.069       0.075
borough_Richmond upon Thames        0.3208      0.030     10.746      0.000       0.262       0.379
borough_Southwark                   0.1845      0.043      4.259      0.000       0.100       0.269
borough_Sutton                     -0.0460      0.033     -1.407      0.159      -0.110       0.018
borough_Tower Hamlets               0.1623      0.044      3.689      0.000       0.076       0.249
borough_Waltham Forest             -0.0133      0.028     -0.473      0.636      -0.069       0.042
borough_Wandsworth                  0.2055      0.050      4.144      0.000       0.108       0.303
borough_Westminster                 0.4215      0.082      5.166      0.000       0.262       0.581
amenity_Wifi                       -0.0156      0.010     -1.553      0.120      -0.035       0.004
amenity_Smoke alarm                -0.0139      0.016     -0.860      0.390      -0.045       0.018
amenity_Kitchen                     0.0161      0.020      0.789      0.430      -0.024       0.056
amenity_Washer                     -0.0209      0.013     -1.617      0.106      -0.046       0.004
amenity_Essentials                  0.0511      0.007      7.065      0.000       0.037       0.065
amenity_Iron                        0.0255      0.019      1.314      0.189      -0.013       0.063
amenity_Hot water                  -0.0993      0.012     -8.167      0.000      -0.123      -0.075
amenity_Hangers                     0.0005      0.009      0.052      0.958      -0.017       0.018
amenity_Carbon monoxide alarm      -0.0113      0.008     -1.404      0.160      -0.027       0.004
amenity_Hair dryer                  0.0420      0.013      3.192      0.001       0.016       0.068
amenity_Heating                    -0.0047      0.006     -0.778      0.436      -0.016       0.007
amenity_Bed linens                 -0.0193      0.008     -2.277      0.023      -0.036      -0.003
amenity_TV                          0.0450      0.010      4.558      0.000       0.026       0.064
amenity_Dishes and silverware      -0.0448      0.013     -3.571      0.000      -0.069      -0.020
amenity_Refrigerator                0.0199      0.007      2.836      0.005       0.006       0.034
amenity_Cooking basics              0.0142      0.009      1.588      0.112      -0.003       0.032
amenity_Shampoo                     0.0070      0.010      0.672      0.502      -0.013       0.028
amenity_Microwave                  -0.0205      0.010     -2.027      0.043      -0.040      -0.001
amenity_Hot water kettle           -0.0198      0.014     -1.437      0.151      -0.047       0.007
amenity_Oven                        0.0124      0.008      1.490      0.136      -0.004       0.029
amenity_Dedicated workspace         0.0283      0.008      3.731      0.000       0.013       0.043
amenity_Toaster                     0.0192      0.010      1.971      0.049       0.000       0.038
amenity_Freezer                     0.0265      0.009      2.992      0.003       0.009       0.044
amenity_Shower gel                  0.0092      0.007      1.261      0.207      -0.005       0.023
amenity_First aid kit              -0.0065      0.007     -0.907      0.365      -0.021       0.008
amenity_Dining table                0.0411      0.007      5.581      0.000       0.027       0.055
amenity_Cleaning products          -0.0111      0.007     -1.528      0.126      -0.025       0.003
amenity_Self check-in              -0.0414      0.010     -4.013      0.000      -0.062      -0.021
amenity_Fire extinguisher           0.0077      0.008      0.956      0.339      -0.008       0.024
amenity_Long term stays allowed    -0.0261      0.008     -3.218      0.001      -0.042      -0.010
==============================================================================
Omnibus:                    26929.856   Durbin-Watson:                   1.876
Prob(Omnibus):                  0.000   Jarque-Bera (JB):          1329205.821
Skew:                           2.373   Prob(JB):                         0.00
Kurtosis:                      29.854   Cond. No.                     4.98e+03
==============================================================================

Notes:
[1] Standard Errors are robust to cluster correlation (cluster)
[2] The condition number is large, 4.98e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

### Double Lasso PDS

In [13]:
#setting up controls, treatment adn outcome

y_lasso = "log_price"
d_lasso = "log_rivals_500m"
fe_lasso = "loc_fe"

#fe columns
fe_cols = [c for c in df.columns if c.startswith("fe_")]

exclude = {y_lasso, d_lasso, "rivals_500m", "price", "id",
            fe_lasso, "log_rivals_c_sq", "log_rivals_c"}

# Candidate controls for selection (exclude FE dummies from selection step)
X_cand_cols = [c for c in df.columns if c not in exclude and c not in fe_cols]

# FE dummies forced-in at the final stage
X_force_cols = fe_cols

### Double selection

In [14]:
#Variabels for lasso
X_cand = df[X_cand_cols].values
Y = df[y_lasso].values.astype(np.float64)
T = df[d_lasso].values.astype(np.float64)

# ElasticNetCV with l1_ratio = 1 for lasso
enet = ElasticNetCV(
    l1_ratio=1.0,
    alphas=None,
    cv=5,
    random_state=0,
    max_iter=10000
)

# Pipeline: standardize then fit
y_selector = Pipeline([("scaler", StandardScaler()), ("enet", enet)])
t_selector = Pipeline([("scaler", StandardScaler()), ("enet", enet)])

y_selector.fit(X_cand, Y)
t_selector.fit(X_cand, T)

coef_y = y_selector.named_steps["enet"].coef_
coef_t = t_selector.named_steps["enet"].coef_

S_y = set(np.array(X_cand_cols)[coef_y != 0])
S_t = set(np.array(X_cand_cols)[coef_t != 0])
S_union = sorted(list(S_y.union(S_t)))

print("Selected for Y:", len(S_y))
print("Selected for T:", len(S_t))
print("Union selected:", len(S_union))

Selected for Y: 90
Selected for T: 90
Union selected: 90

In [15]:
removed = [c for c in X_cand_cols if c not in S_union]
removed

['amenity_Washer', 'amenity_Cooking basics', 'amenity_Hot water kettle']

In [16]:
difference = [c for c in S_y if c not in S_t]
difference

[]

### PDS

In [17]:
Z_cols = [d_lasso] + S_union + X_force_cols
Z_lasso = df[Z_cols].copy()
Z_lasso = Z_lasso.astype(float)
Z_lasso = sm.add_constant(Z_lasso, has_constant="add")

pds = sm.OLS(df[y_lasso].values, Z_lasso).fit(
    cov_type="cluster",
    cov_kwds={"groups": df[fe_lasso]}
)

print(pds.summary())
print("\nPDS beta:", pds.params[d_lasso], "SE:", pds.bse[d_lasso])

                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.727
Model:                            OLS   Adj. R-squared:                  0.725
Method:                 Least Squares   F-statistic:                 2.269e+04
Date:                Thu, 26 Feb 2026   Prob (F-statistic):          2.25e-187
Time:                        16:55:22   Log-Likelihood:                -20688.
No. Observations:               42898   AIC:                         4.176e+04
Df Residuals:                   42707   BIC:                         4.341e+04
Df Model:                         190
Covariance Type:              cluster
===================================================================================================
                                      coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------------------------
const                               4.3375      0.111     39.101      0.000       4.120       4.555
log_rivals_500m                     0.0186      0.012      1.532      0.126      -0.005       0.042
about_dummy                         0.0070      0.008      0.833      0.405      -0.010       0.024
accommodates                        0.0827      0.004     18.541      0.000       0.074       0.091
amenity_Bed linens                 -0.0098      0.007     -1.311      0.190      -0.025       0.005
amenity_Carbon monoxide alarm      -0.0057      0.008     -0.678      0.498      -0.022       0.011
amenity_Cleaning products          -0.0112      0.007     -1.625      0.104      -0.025       0.002
amenity_Dedicated workspace         0.0280      0.007      3.855      0.000       0.014       0.042
amenity_Dining table                0.0390      0.007      5.688      0.000       0.026       0.052
amenity_Dishes and silverware      -0.0378      0.010     -3.611      0.000      -0.058      -0.017
amenity_Essentials                  0.0543      0.007      7.909      0.000       0.041       0.068
amenity_Fire extinguisher           0.0089      0.008      1.157      0.247      -0.006       0.024
amenity_First aid kit              -0.0026      0.007     -0.377      0.706      -0.016       0.011
amenity_Freezer                     0.0227      0.008      2.888      0.004       0.007       0.038
amenity_Hair dryer                  0.0319      0.010      3.071      0.002       0.012       0.052
amenity_Hangers                    -0.0044      0.009     -0.478      0.632      -0.022       0.014
amenity_Heating                    -0.0074      0.005     -1.380      0.168      -0.018       0.003
amenity_Hot water                  -0.0940      0.012     -7.704      0.000      -0.118      -0.070
amenity_Iron                        0.0260      0.018      1.429      0.153      -0.010       0.062
amenity_Kitchen                     0.0107      0.016      0.680      0.497      -0.020       0.042
amenity_Long term stays allowed    -0.0302      0.008     -4.026      0.000      -0.045      -0.016
amenity_Microwave                  -0.0270      0.010     -2.821      0.005      -0.046      -0.008
amenity_Oven                        0.0055      0.009      0.601      0.548      -0.013       0.024
amenity_Refrigerator                0.0213      0.007      3.107      0.002       0.008       0.035
amenity_Self check-in              -0.0308      0.009     -3.550      0.000      -0.048      -0.014
amenity_Shampoo                     0.0036      0.010      0.354      0.724      -0.016       0.023
amenity_Shower gel                  0.0058      0.008      0.692      0.489      -0.011       0.022
amenity_Smoke alarm                -0.0164      0.016     -1.015      0.310      -0.048       0.015
amenity_TV                          0.0425      0.009      4.515      0.000       0.024       0.061
amenity_Toaster                     0.0171      0.008      2.239      0.025       0.002       0.032
amenity_Wifi                       -0.0215      0.008     -2.722      0.006      -0.037      -0.006
bathrooms                           0.0953      0.013      7.593      0.000       0.071       0.120
bedrooms                            0.1527      0.010     15.341      0.000       0.133       0.172
beds                               -0.0248      0.005     -5.303      0.000      -0.034      -0.016
borough_Barnet                      0.0545      0.087      0.625      0.532      -0.116       0.225
borough_Bexley                     -0.0745      0.064     -1.166      0.244      -0.200       0.051
borough_Brent                       0.1947      0.085      2.291      0.022       0.028       0.361
borough_Bromley                     0.0794      0.096      0.825      0.410      -0.109       0.268
borough_Camden                      0.1246      0.075      1.672      0.095      -0.021       0.271
borough_City of London              0.3190      0.068      4.665      0.000       0.185       0.453
borough_Croydon                     0.1338      0.099      1.351      0.177      -0.060       0.328
borough_Ealing                      0.1984      0.090      2.216      0.027       0.023       0.374
borough_Enfield                     0.1246      0.075      1.668      0.095      -0.022       0.271
borough_Greenwich                  -0.0127      0.079     -0.162      0.872      -0.167       0.142
borough_Hackney                    -0.0208      0.063     -0.332      0.740      -0.144       0.102
borough_Hammersmith and Fulham      0.2401      0.097      2.487      0.013       0.051       0.429
borough_Haringey                    0.0900      0.079      1.139      0.255      -0.065       0.245
borough_Harrow                      0.1566      0.098      1.597      0.110      -0.036       0.349
borough_Havering                    0.0680      0.050      1.351      0.177      -0.031       0.167
borough_Hillingdon                  0.1511      0.094      1.605      0.108      -0.033       0.336
borough_Hounslow                    0.3153      0.096      3.300      0.001       0.128       0.503
borough_Islington                   0.0712      0.066      1.073      0.283      -0.059       0.201
borough_Kensington and Chelsea      0.2902      0.092      3.144      0.002       0.109       0.471
borough_Kingston upon Thames        0.2422      0.100      2.418      0.016       0.046       0.439
borough_Lambeth                     0.1145      0.082      1.404      0.160      -0.045       0.274
borough_Lewisham                   -0.0866      0.077     -1.124      0.261      -0.238       0.064
borough_Merton                      0.2173      0.112      1.941      0.052      -0.002       0.437
borough_Newham                     -0.0357      0.067     -0.532      0.595      -0.168       0.096
borough_Redbridge                  -0.0325      0.060     -0.539      0.590      -0.151       0.086
borough_Richmond upon Thames        0.4336      0.097      4.467      0.000       0.243       0.624
borough_Southwark                  -0.0450      0.088     -0.514      0.607      -0.217       0.127
borough_Sutton                      0.2713      0.184      1.476      0.140      -0.089       0.632
borough_Tower Hamlets              -0.0323      0.063     -0.513      0.608      -0.156       0.091
borough_Waltham Forest             -0.1024      0.058     -1.776      0.076      -0.216       0.011
borough_Wandsworth                  0.2093      0.110      1.900      0.057      -0.007       0.425
borough_Westminster                 0.2733      0.083      3.291      0.001       0.111       0.436
calculated_host_listings_count      0.0015      0.000     11.171      0.000       0.001       0.002
desc_dummy                         -0.1437      0.025     -5.794      0.000      -0.192      -0.095
entire                              0.0017      0.032      0.053      0.957      -0.061       0.064
experience                          0.0036      0.001      3.777      0.000       0.002       0.005
host_acceptance_rate               -0.0484      0.013     -3.760      0.000      -0.074      -0.023
host_has_profile_pic                0.0276      0.019      1.435      0.151      -0.010       0.065
host_identity_verified             -0.0246      0.012     -2.013      0.044      -0.049      -0.001
host_is_superhost                   0.1017      0.012      8.699      0.000       0.079       0.125
host_listings_count                 0.0038      0.012      0.322      0.748      -0.019       0.027
host_response_rate                 -0.0061      0.021     -0.295      0.768      -0.046       0.034
host_total_listings_count          -0.0259      0.010     -2.648      0.008      -0.045      -0.007
host_verifications                  0.0224      0.010      2.354      0.019       0.004       0.041
instant_bookable                    0.0139      0.008      1.767      0.077      -0.002       0.029
maximum_nights                      0.0117      0.003      4.220      0.000       0.006       0.017
minimum_nights                     -0.0005      0.000     -2.672      0.008      -0.001      -0.000
number_of_reviews                  -0.0007   5.18e-05    -12.677      0.000      -0.001      -0.001
overveiw_dummy                      0.0257      0.008      3.318      0.001       0.011       0.041
private                            -0.6042      0.037    -16.229      0.000      -0.677      -0.531
review_scores_accuracy             -0.0360      0.011     -3.137      0.002      -0.059      -0.014
review_scores_checkin              -0.0610      0.008     -7.295      0.000      -0.077      -0.045
review_scores_cleanliness           0.1307      0.011     11.435      0.000       0.108       0.153
review_scores_communication        -0.0647      0.011     -5.631      0.000      -0.087      -0.042
review_scores_location              0.0743      0.015      4.836      0.000       0.044       0.104
review_scores_rating                0.1312      0.015      8.483      0.000       0.101       0.161
review_scores_value                -0.1041      0.011     -9.181      0.000      -0.126      -0.082
shared                             -1.2436      0.102    -12.164      0.000      -1.444      -1.043
fe_1                               -0.4738      0.071     -6.711      0.000      -0.612      -0.335
fe_2                               -0.5479      0.074     -7.403      0.000      -0.693      -0.403
fe_3                               -0.4534      0.069     -6.615      0.000      -0.588      -0.319
fe_4                               -0.4713      0.059     -8.021      0.000      -0.586      -0.356
fe_5                               -0.6079      0.063     -9.634      0.000      -0.732      -0.484
fe_6                               -0.2194      0.065     -3.359      0.001      -0.347      -0.091
fe_7                               -0.6611      0.079     -8.398      0.000      -0.815      -0.507
fe_8                               -0.5125      0.063     -8.117      0.000      -0.636      -0.389
fe_9                               -0.4876      0.061     -7.965      0.000      -0.608      -0.368
fe_10                              -0.6026      0.071     -8.545      0.000      -0.741      -0.464
fe_11                              -0.3347      0.020    -16.455      0.000      -0.375      -0.295
fe_12                              -0.4571      0.045    -10.115      0.000      -0.546      -0.369
fe_13                              -0.5451      0.065     -8.338      0.000      -0.673      -0.417
fe_14                              -0.7584      0.073    -10.382      0.000      -0.902      -0.615
fe_15                              -0.6071      0.079     -7.637      0.000      -0.763      -0.451
fe_16                              -0.3316      0.057     -5.792      0.000      -0.444      -0.219
fe_17                              -0.1433      0.064     -2.242      0.025      -0.269      -0.018
fe_18                              -0.9901      0.174     -5.683      0.000      -1.332      -0.649
fe_19                              -0.3097      0.057     -5.414      0.000      -0.422      -0.198
fe_20                              -0.4864      0.070     -6.929      0.000      -0.624      -0.349
fe_21                              -0.5673      0.065     -8.784      0.000      -0.694      -0.441
fe_22                              -0.7123      0.055    -12.934      0.000      -0.820      -0.604
fe_23                              -0.3007      0.077     -3.910      0.000      -0.451      -0.150
fe_24                              -0.8433      0.066    -12.749      0.000      -0.973      -0.714
fe_25                              -0.6727      0.062    -10.763      0.000      -0.795      -0.550
fe_26                              -0.6441      0.056    -11.408      0.000      -0.755      -0.533
fe_27                              -0.7629      0.091     -8.405      0.000      -0.941      -0.585
fe_28                              -0.0342      0.040     -0.864      0.388      -0.112       0.043
fe_29                              -0.5606      0.083     -6.769      0.000      -0.723      -0.398
fe_30                              -0.8654      0.068    -12.726      0.000      -0.999      -0.732
fe_31                              -0.3016      0.060     -5.024      0.000      -0.419      -0.184
fe_32                              -0.6160      0.071     -8.657      0.000      -0.755      -0.477
fe_33                              -0.6089      0.076     -7.974      0.000      -0.759      -0.459
fe_34                              -0.5240      0.017    -30.637      0.000      -0.558      -0.491
fe_35                              -0.6019      0.058    -10.369      0.000      -0.716      -0.488
fe_36                              -0.4363      0.072     -6.079      0.000      -0.577      -0.296
fe_37                              -0.5809      0.070     -8.291      0.000      -0.718      -0.444
fe_38                              -0.7153      0.076     -9.458      0.000      -0.863      -0.567
fe_39                              -0.5889      0.066     -8.938      0.000      -0.718      -0.460
fe_40                              -0.0347      0.047     -0.743      0.457      -0.126       0.057
fe_41                              -0.5827      0.070     -8.318      0.000      -0.720      -0.445
fe_42                              -0.6966      0.080     -8.675      0.000      -0.854      -0.539
fe_43                              -0.3334      0.062     -5.369      0.000      -0.455      -0.212
fe_44                              -0.4907      0.056     -8.706      0.000      -0.601      -0.380
fe_45                              -0.7406      0.048    -15.342      0.000      -0.835      -0.646
fe_46                              -0.5028      0.029    -17.088      0.000      -0.560      -0.445
fe_47                              -0.3955      0.052     -7.596      0.000      -0.498      -0.293
fe_48                              -0.3320      0.054     -6.197      0.000      -0.437      -0.227
fe_49                              -0.5826      0.079     -7.355      0.000      -0.738      -0.427
fe_50                              -0.3584      0.082     -4.344      0.000      -0.520      -0.197
fe_51                              -0.4268      0.072     -5.962      0.000      -0.567      -0.287
fe_52                              -0.2438      0.023    -10.405      0.000      -0.290      -0.198
fe_53                              -0.6161      0.076     -8.101      0.000      -0.765      -0.467
fe_54                              -0.6350      0.034    -18.794      0.000      -0.701      -0.569
fe_55                              -0.7311      0.078     -9.330      0.000      -0.885      -0.577
fe_56                              -0.6024      0.068     -8.803      0.000      -0.737      -0.468
fe_57                              -0.5483      0.081     -6.739      0.000      -0.708      -0.389
fe_58                              -0.3722      0.068     -5.489      0.000      -0.505      -0.239
fe_59                              -0.3491      0.064     -5.420      0.000      -0.475      -0.223
fe_60                              -0.2347      0.058     -4.075      0.000      -0.348      -0.122
fe_61                              -0.5282      0.082     -6.453      0.000      -0.689      -0.368
fe_62                              -0.4484      0.046     -9.777      0.000      -0.538      -0.358
fe_63                              -0.6648      0.066    -10.022      0.000      -0.795      -0.535
fe_64                              -0.5096      0.066     -7.752      0.000      -0.638      -0.381
fe_65                              -0.7590      0.095     -8.015      0.000      -0.945      -0.573
fe_66                              -0.1645      0.060     -2.730      0.006      -0.283      -0.046
fe_67                              -0.9049      0.157     -5.756      0.000      -1.213      -0.597
fe_68                              -0.5787      0.076     -7.650      0.000      -0.727      -0.430
fe_69                              -0.5320      0.079     -6.747      0.000      -0.687      -0.377
fe_70                              -0.5256      0.086     -6.079      0.000      -0.695      -0.356
fe_71                              -0.6062      0.081     -7.491      0.000      -0.765      -0.448
fe_72                              -0.5758      0.053    -10.831      0.000      -0.680      -0.472
fe_73                              -0.3860      0.055     -7.023      0.000      -0.494      -0.278
fe_74                              -0.3522      0.078     -4.509      0.000      -0.505      -0.199
fe_75                              -0.2293      0.079     -2.912      0.004      -0.384      -0.075
fe_76                              -0.5961      0.067     -8.833      0.000      -0.728      -0.464
fe_77                              -0.3535      0.079     -4.459      0.000      -0.509      -0.198
fe_78                              -0.2633      0.046     -5.678      0.000      -0.354      -0.172
fe_79                              -0.4709      0.074     -6.360      0.000      -0.616      -0.326
fe_80                              -0.3239      0.019    -17.117      0.000      -0.361      -0.287
fe_81                              -0.4013      0.057     -7.000      0.000      -0.514      -0.289
fe_82                              -0.5721      0.065     -8.863      0.000      -0.699      -0.446
fe_83                              -0.8742      0.074    -11.854      0.000      -1.019      -0.730
fe_84                              -0.3964      0.078     -5.060      0.000      -0.550      -0.243
fe_85                              -0.3498      0.046     -7.560      0.000      -0.440      -0.259
fe_86                              -0.1409      0.055     -2.580      0.010      -0.248      -0.034
fe_87                              -0.7070      0.084     -8.402      0.000      -0.872      -0.542
fe_88                              -0.7052      0.077     -9.124      0.000      -0.857      -0.554
fe_89                              -0.6399      0.062    -10.403      0.000      -0.760      -0.519
fe_90                              -0.5705      0.069     -8.238      0.000      -0.706      -0.435
fe_91                              -0.6595      0.061    -10.753      0.000      -0.780      -0.539
fe_92                              -0.1819      0.078     -2.324      0.020      -0.335      -0.028
fe_93                              -0.0418      0.008     -5.460      0.000      -0.057      -0.027
fe_94                              -0.6739      0.072     -9.319      0.000      -0.816      -0.532
fe_95                              -0.6681      0.075     -8.945      0.000      -0.814      -0.522
fe_96                              -0.2736      0.051     -5.392      0.000      -0.373      -0.174
fe_97                              -0.8773      0.079    -11.117      0.000      -1.032      -0.723

c:\Users\danil\anaconda3\envs\vair312\Lib\site-packages\statsmodels\base\model.py:1894: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 190, but rank is 91
  warnings.warn('covariance of constraints does not have full '

### DML

In [18]:
X_dml = df[X_cand_cols + X_force_cols].values
X_dml = X_dml.astype(np.float64)

dml = LinearDML(
    model_y=RandomForestRegressor(
        n_estimators=300,
        min_samples_leaf=20,
        n_jobs=-1,
        random_state=0
    ),
    model_t=RandomForestRegressor(
        n_estimators=300,
        min_samples_leaf=20,
        n_jobs=-1,
        random_state=0
    ),
    discrete_treatment=False,
    cv=KFold(n_splits=5, shuffle=True, random_state=0),
    random_state=0
)

dml.fit(Y, T, X=X_dml)

In [19]:
ate = dml.ate(X=X_dml)
print("Flexible DML ATE:", ate)

Flexible DML ATE: 0.009708573592984984

In [20]:
ci = dml.ate_interval(X=X_dml)
print("CI:", ci)

CI: (np.float64(-0.0007030316084277819), np.float64(0.020120178794397828))

### Causal forest

In [21]:
cf = CausalForestDML(
    model_y=RandomForestRegressor(n_estimators=300,
                                   min_samples_leaf=20, n_jobs=-1,
                                     random_state=0),
    model_t=RandomForestRegressor(n_estimators=300,
                                   min_samples_leaf=20, n_jobs=-1,
                                     random_state=0),
    n_estimators=1000,
    min_samples_leaf=50,
    random_state=42
)

cf.fit(Y, T, X=X_dml)

### Treatment heterogenity

In [22]:
cate = cf.effect(X_dml)
np.percentile(cate, [5, 25, 50, 75, 95])

array([-0.01877677,  0.01206159,  0.02750994,  0.0400592 ,  0.06169013])

In [23]:
dist_cate = px.histogram(
    x=cate,
    labels={"x": "TE"},
    title="Treatment Effect Distribution"
)
dist_cate.show()

## Results table

In [24]:
treat = "log_rivals_500m"

b1, se1, n1, r21 = sm_extract(ols1, treat)
b2, se2, n2, r22 = sm_extract(ols2, treat)
b3, se3, n3, r23 = sm_extract(pds, treat)

ate_dml, _, lo_dml, hi_dml = econml_ate_row(dml, X=X_dml)
ate_cf, _, lo_cf, hi_cf = econml_ate_row(cf, X=X_dml)
n_dml = len(X_dml)
n_cf = len(X_dml)

In [25]:
table = pd.DataFrame({
    "(1) OLS": [
        f"{b1:.4f}",
        f"({se1:.4f})",
        "Yes",
        "No",
        f"{n1}",
        f"{r21:.3f}"
    ],
    "(2) OLS + FE": [
        f"{b2:.4f}",
        f"({se2:.4f})",
        "Yes",
        "Yes",
        f"{n2}",
        f"{r22:.3f}"
    ],
    "(3) PDS": [
        f"{b3:.4f}",
        f"({se3:.4f})",
        "Selected via Lasso",
        "Yes",
        f"{n3}",
        f"{r23:.3f}"
    ],
    "(4) Linear DML": [
        f"{ate_dml:.4f}",
        f"[{lo_dml:.4f}, {hi_dml:.4f}]",
        "ML-adjusted",
        "Yes",
        f"{n_dml}",
        ""
    ],
    "(5) Causal Forest": [
        f"{ate_cf:.4f}",
        f"[{lo_cf:.4f}, {hi_cf:.4f}]",
        "ML-adjusted",
        "Yes",
        f"{n_cf}",
        ""
    ]
},
index=[
    "Log rivals (500m)",
    "",
    "Controls",
    "Location FE",
    "Observations",
    "R-squared"
])

table

,(1) OLS,(2) OLS + FE,(3) PDS,(4) Linear DML,(5) Causal Forest
Log rivals (500m),0.0722,0.0187,0.0186,0.0097,0.0252
,(0.0123),(0.0122),(0.0122),"[-0.0007, 0.0201]","[-0.0154, 0.0658]"
Controls,Yes,Yes,Selected via Lasso,ML-adjusted,ML-adjusted
Location FE,No,Yes,Yes,Yes,Yes
Observations,42898,42898,42898,42898,42898
R-squared,0.706,0.727,0.727,,